
// student

export const STUDENTS_REQUEST = "STUDENTS_REQUEST";
export const STUDENTS_SUCCESS = "STUDENTS_SUCCESS";
export const STUDENTS_FAIL = "STUDENTS_FAIL";

// createStudent

export const CREATESTUDENT_REQUEST = "CREATESTUDENT_REQUEST";
export const CREATESTUDENT_SUCCESS = "CREATESTUDENT_SUCCESS";
export const CREATESTUDENT_FAIL = "CREATESTUDENT_FAIL";


//studentView

export const STUDENTVIEW_REQUEST = "STUDENTVIEW_REQUEST";
export const STUDENTVIEW_SUCCESS = "STUDENTVIEW_SUCCESS";
export const STUDENTVIEW_FAIL = "STUDENTVIEW_FAIL";

// studentDelete 

export const STUDENTDELETE_REQUEST = "STUDENTDELETE_REQUEST";
export const STUDENTDELETE_SUCCESS = "STUDENTDELETE_SUCCESS";
export const STUDENTDELETE_FAIL = "STUDENTDELETE_FAIL";

// studentUpdate 

export const STUDENTUPDATE_REQUEST = "STUDENTUPDATE_REQUEST";
export const STUDENTUPDATE_SUCCESS = "STUDENTUPDATE_SUCCESS";
export const STUDENTUPDATE_FAIL = "STUDENTUPDATE_FAIL";

// studentCourse

export const STUDENTCOURSE_REQUEST = "STUDENTCOURSE_REQUEST";
export const STUDENTCOURSE_SUCCESS = "STUDENTCOURSE_SUCCESS";
export const STUDENTCOURSE_FAIL = "STUDENTCOURSE_FAIL";

// studentCourseCreate

export const STUDENTCOURSECREATE_REQUEST = "STUDENTCOURSECREATE_REQUEST";
export const STUDENTCOURSECREATE_SUCCESS = "STUDENTCOURSECREATE_SUCCESS";
export const STUDENTCOURSECREATE_FAIL = "STUDENTCOURSECREATE_FAIL";

// studentCourseDelete


export const STUDENTCOURSEDELETE_REQUEST = "STUDENTCOURSEDELETE_REQUEST";
export const STUDENTCOURSEDELETE_SUCCESS = "STUDENTCOURSEDELETE_SUCCESS";
export const STUDENTCOURSEDELETE_FAIL = "STUDENTCOURSEDELETE_FAIL";














































