
// courseCategory

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

// createCategory

export const CREATECATEGORY_REQUEST = "CREATECATEGORY_REQUEST";
export const CREATECATEGORY_SUCCESS = "CREATECATEGORY_SUCCESS";
export const CREATECATEGORY_FAIL = "CREATECATEGORY_FAIL";


// deleteCategory

export const DELETECATEGORY_REQUEST = "DELETECATEGORY_REQUEST";
export const DELETECATEGORY_SUCCESS = "DELETECATEGORY_SUCCESS";
export const DELETECATEGORY_FAIL = "DELETECATEGORY_FAIL";

// categoryView

export const CATEGORYVIEW_REQUEST = "CATEGORYVIEW_REQUEST";
export const CATEGORYVIEW_SUCCESS = "CATEGORYVIEW_SUCCESS";
export const CATEGORYVIEW_FAIL = "CATEGORYVIEW_FAIL";

// updateCategory

export const UPDATECATEGORY_REQUEST = "UPDATECATEGORY_REQUEST";
export const UPDATECATEGORY_SUCCESS = "UPDATECATEGORY_SUCCESS";
export const UPDATECATEGORY_FAIL = "UPDATECATEGORY_FAIL";

