
// courses

export const COURSE_REQUEST = "COURSE_REQUEST";
export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_FAIL = "COURSE_FAIL";

// createCourse

export const CREATECOURSE_REQUEST = "CREATECOURSE_REQUEST";
export const CREATECOURSE_SUCCESS = "CREATECOURSE_SUCCESS";
export const CREATECOURSE_FAIL = "CREATECOURSE_FAIL";

// courseView

export const COURSEVIEW_REQUEST = "COURSEVIEW_REQUEST";
export const COURSEVIEW_SUCCESS = "COURSEVIEW_SUCCESS";
export const COURSEVIEW_FAIL = "COURSEVIEW_FAIL";

// deleteCourse

export const DELETECOURSE_REQUEST = "DELETECOURSE_REQUEST";
export const DELETECOURSE_SUCCESS = "DELETECOURSE_SUCCESS";
export const DELETECOURSE_FAIL = "DELETECOURSE_FAIL";


// updateCourse

export const UPDATECOURSE_REQUEST = "UPDATECOURSE_REQUEST";
export const UPDATECOURSE_SUCCESS = "UPDATECOURSE_SUCCESS";
export const UPDATECOURSE_FAIL = "UPDATECOURSE_FAIL";




